### PR TITLE
Helm chart improvements

### PR DESCRIPTION
**Pull request by rubenharutyunov**
This PR makes the following improvements to the Helm chart:
* `bitnami/kubectl` is updated to 1.24.10. This version has arm64 support.
* Added support for `nodeSelector`, `affinity` and `tolerations` to have more control on scheduling.
* Fixed default values for `ingress.annotations` (should be map, instead of the list). Wrong default was causing `cannot overwrite table with non table` warning with custom values file.
* `test-connection` for stream now runs only when stream component is enabled. 

Test plan:
* Used the following values file to test:
```
server:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      alb.ingress.kubernetes.io/group.name: cluster
    tls: []
    hosts:
      - host: convoy.example.com
        http:
          paths:
            - path: /
              pathType: Prefix
  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - antarctica-east1
                  - antarctica-west1

ingest:
  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - antarctica-east1
                  - antarctica-west1
migrate:
  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - antarctica-east1
                  - antarctica-west1

stream:
  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - antarctica-east1
                  - antarctica-west1

worker:
  nodeSelector:
    kubernetes.io/arch: amd64

  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - antarctica-east1
                  - antarctica-west1
```
* Verified (visually) with `helm template -f ~/convoy/convoy-values.yaml convoy . -n convoy` 
* Verified with `helm template -f ~/convoy/convoy-values.yaml convoy . -n convoy | kubectl apply --dry-run=server -n convoy -f -`
* Deployed the same changes on our environment (with updated values file).

### CODE REVIEW

**Comment by rubenharutyunov** [comment]
@jirevwe can you please have a look?

**Comment by jirevwe** [comment]
LGTM

**Review by jirevwe — APPROVED** [review]

**Comment by jirevwe** [comment]
Yes, I'll release it. Been attending to some other things.

**Comment by jirevwe** [comment]
Done.

**Pull request merged**
