### PR TITLE
Allow to provide passwords values from secrets

### PR DESCRIPTION
**Pull request by itek09**
The intention of this PR is to provide the passwords from secrets values instead of plaintext.

Plaintext is still supported.

### CODE REVIEW

**Comment by itek09** [comment]
@jirevwe If you can take a quick look here :)

I created a fork of the project and I'm already using this, let me know if you consider that anything needs to be changed.

Many thanks and sorry for direct ping.

**Comment by jirevwe** [comment]
No worries, can't believe I missed this. 

I'll take a look at it and revert.

**Review by jirevwe — APPROVED** [review]

**Comment by jirevwe** [comment]
LGTM, I'll merge and release the charts

**Comment by itek09** [comment]
Many thanks!

**Comment by jirevwe** [comment]
It's been [released](https://github.com/frain-dev/helm-charts/releases/tag/convoy-2.0.0). Please give it about 30 mins to propagate to artifacthub.io

**Pull request merged**
